---
driver:
  name: lxd_cli
  network:
    - ["forwarded_port", {guest: 80, host: 9080}]
    - ["forwarded_port", {guest: 443, host: 9443}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[tcr-datasets::default]
    attributes:
